"""Crops a single iso tile generated by Leonardo (white background) and writes
it to public/assets/tiles/forest/path-01.png.
"""
from pathlib import Path
import numpy as np
from PIL import Image

REPO = Path(__file__).resolve().parent.parent
SRC = REPO / "shareAI" / "assetsTLOD" / "maps" / "02_forest" / "tiles" / "02_forest_dirt_001.jpg"
OUT = REPO / "public" / "assets" / "tiles" / "forest" / "path-01.png"

WHITE_THRESH = 200  # JPG bg is noisy, threshold conservatively low to clip true content


def main() -> None:
    img = Image.open(SRC).convert("RGB")
    arr = np.array(img)
    is_fg = (arr[..., 0] < WHITE_THRESH) | (arr[..., 1] < WHITE_THRESH) | (arr[..., 2] < WHITE_THRESH)
    ys, xs = np.where(is_fg)
    if len(xs) == 0:
        raise SystemExit("no foreground pixels detected — adjust threshold")
    pad = 4
    bbox = (
        max(0, int(xs.min()) - pad),
        max(0, int(ys.min()) - pad),
        min(arr.shape[1], int(xs.max()) + pad),
        min(arr.shape[0], int(ys.max()) + pad),
    )
    cropped = img.crop(bbox)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    cropped.save(OUT)
    print(f"wrote {OUT.relative_to(REPO)}  bbox={bbox}  size={cropped.size}")


if __name__ == "__main__":
    main()
